name: mlops-governance-reference

services:
  # ==========================================
  # API GATEWAY (Nginx)
  # ==========================================
  api-gateway:
    image: nginx:1.25-alpine
    container_name: mlops-api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fraud-detection-api
      - loan-default-api
      - aml-streaming-api
    restart: unless-stopped

  # ==========================================
  # PROJECT 1: Credit Card Fraud API
  # ==========================================
  fraud-detection-api:
    image: ghcr.io/satyaifd/mlops-governance-reference/fraud-detection-job:latest
    container_name: mlops-fraud-api
    restart: unless-stopped

  # ==========================================
  # PROJECT 2: Loan Default API
  # ==========================================
  loan-default-api:
    image: ghcr.io/satyaifd/mlops-governance-reference/loan-default-job:latest
    container_name: mlops-loan-api
    restart: unless-stopped

  # ==========================================
  # PROJECT 3: Real-Time AML Streaming API
  # ==========================================
  aml-streaming-api:
    image: ghcr.io/satyaifd/mlops-governance-reference/aml-stream-api:latest
    container_name: mlops-aml-streaming
    restart: unless-stopped
