"""
Automated Regulatory Governance & Auditing Engine - Project 2
Compiles statistical evaluation and drift metrics into a formal markdown Model Card.
"""

import json
import sys
from pathlib import Path

# Align project root on path context for imports
GOV_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = GOV_DIR.parents[1]
sys.path.append(str(PROJECT_ROOT))

def compile_compliance_audit():
    """Reads runtime JSON metrics and auto-generates a Markdown Model Card report."""
    artifacts_dir = PROJECT_ROOT / "artifacts"
    docs_dir = PROJECT_ROOT / "docs"
    
    # Paths to source metric files
    eval_report_path = artifacts_dir / "compliance_audit_report.json"
    drift_report_path = artifacts_dir / "data_drift_report.json"
    model_card_path = docs_dir / "model_card.md"

    print("🔍 Inspecting performance and drift artifacts for regulatory review...")

    # Load metrics with safe fallbacks if files don't exist yet
    eval_data = {}
    if eval_report_path.exists():
        with open(eval_report_path, "r") as f:
            eval_data = json.load(f)
            
    drift_data = {}
    if drift_report_path.exists():
        with open(drift_report_path, "r") as f:
            drift_data = json.load(f)

    # Extract relevant variables for report compilation
    fairness_status = eval_data.get("fairness_metrics", {}).get("demographic_parity_status", "UNKNOWN")
    disparate_impact_ratio = eval_data.get("fairness_metrics", {}).get("disparate_impact_ratio", "N/A")
    accuracy = eval_data.get("performance_metrics", {}).get("accuracy", "N/A")
    drift_status = "DRIFT DETECTED" if drift_data.get("drift_detected_alert", False) else "STABLE"

    # Construct the automated markdown string
    markdown_content = f"""# 📑 Automated Model Card & Compliance Audit Report
**Project 2: Loan Default Risk Underwriting Engine**

---

## ⚖️ Model Governance & Fairness Summary
* **Demographic Parity Status:** `{fairness_status}`
* **Disparate Impact Ratio (Young vs. Control Group):** `{disparate_impact_ratio}`
> *Note: Compliance requires the disparate impact ratio to sit between 0.80 and 1.25 to meet the industry standard 4/5ths rule for fair lending practices.*

## 📊 Core Performance Metrics
* **Model Accuracy Status:** `{accuracy}`
* **Underwriting Decision Mode:** Equalized Odds Mitigation Constraints Applied

## 📡 Population Stability & Production Drift
* **Data Distribution Status:** `{drift_status}`
* **Calculated Features Monitored:**
"""
    
    # Loop through individual feature drift evaluations if available
    metrics = drift_data.get("metrics", {})
    if metrics:
        for feature, info in metrics.items():
            markdown_content += f"  * **{feature}:** PSI = `{info.get('psi_value')}` [{info.get('status')}]\n"
    else:
        markdown_content += "  * No live drift telemetry registered.\n"

    markdown_content += f"""
---
*Report auto-generated by the Automated Governance Engine on an active MLOps deployment.*
"""

    # Write the compiled content directly to disk
    docs_dir.mkdir(parents=True, exist_ok=True)
    with open(model_card_path, "w") as f:
        f.write(markdown_content.strip())
        
    print(f"🎉 Governance Audit complete. Updated compliance sheet exported to: {model_card_path}")

if __name__ == "__main__":
    compile_compliance_audit()